// Generated by CoffeeScript 1.3.3
(function() {

  require.config({
    baseUrl: 'javascripts',
    paths: {
      jquery: 'libs/jquery.min',
      backbone: 'libs/backbone-min',
      underscore: 'libs/underscore-min',
      modernizr: "libs/modernizr.foundation",
      d3: 'amd-d3',
      order: 'libs/rjs-plugins/order',
      text: 'libs/rjs-plugins/text',
      json: 'libs/rjs-plugins/json'
    },
    priority: ['modernizr', 'underscore', 'jquery']
  });

  require(['app'], function(Demo) {
    return window.demo = new Demo;
  });

}).call(this);
